version: "3.1"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["./wait-for-mongo.sh", "npm", "start"]